import { useMemo, useState } from 'react';
import Button from '../Button';
import Badge from '../Badge';
import { Input } from '../Form';
import { cn, formatPrice } from '../../lib/utils';
import { t, t2 } from '../../lib/i18n';
import type {
  DiffFlag,
  PreviewDiff,
  PreviewResponse,
  PreviewSummary,
} from '../../lib/bulk';

type Tab = 'attention' | 'all' | 'summary';
type RowFilter = 'all' | 'changed' | 'unchanged' | 'with_flag';

const FLAG_META: Record<DiffFlag, { keyName: string; defaultLabel: string; tone: 'warn' | 'error' | 'info' }> = {
  truncated:         { keyName: 'preview.flag.truncated',         defaultLabel: 'Truncated',         tone: 'warn'  },
  pattern_mismatch:  { keyName: 'preview.flag.pattern_mismatch',  defaultLabel: 'Invalid format',    tone: 'error' },
  below_min_clamped: { keyName: 'preview.flag.below_min_clamped', defaultLabel: 'Clamped to min',    tone: 'warn'  },
  empty_old:         { keyName: 'preview.flag.empty_old',         defaultLabel: 'Empty source',      tone: 'info'  },
  conflict_gt:       { keyName: 'preview.flag.conflict_gt',       defaultLabel: 'Exceeds related',   tone: 'warn'  },
  same_value_batch:  { keyName: 'preview.flag.same_value_batch',  defaultLabel: 'Duplicate across batch', tone: 'error' },
  fallback_to_name:  { keyName: 'preview.flag.fallback_to_name',  defaultLabel: 'Used name as fallback', tone: 'info' },
  empty_source:      { keyName: 'preview.flag.empty_source',      defaultLabel: 'Source empty',      tone: 'info'  },
  ai_generate:       { keyName: 'preview.flag.ai_generate',       defaultLabel: 'Generated by AI at apply', tone: 'info' },
  copy_from_invalid: { keyName: 'preview.flag.copy_from_invalid', defaultLabel: 'Invalid source field',      tone: 'error' },
};

const flagLabel = (f: DiffFlag) => t(FLAG_META[f].keyName, FLAG_META[f].defaultLabel);

interface Props {
  data: PreviewResponse;
  onDownloadCsv: () => void;
}

export default function PreviewPanel({ data, onDownloadCsv }: Props) {
  const { summary, diffs, total_scope, analyzed, truncated } = data;

  const [tab, setTab] = useState<Tab>(() => (summary.with_flags > 0 ? 'attention' : 'all'));
  const [filter, setFilter] = useState<RowFilter>('all');
  const [flagFilter, setFlagFilter] = useState<DiffFlag | null>(null);
  const [fieldFilter, setFieldFilter] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  const PAGE_SIZE = 20;

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    return diffs.filter((d) => {
      if (q) {
        const hit = String(d.id_product).includes(q) ||
          d.name.toLowerCase().includes(q) ||
          (d.reference || '').toLowerCase().includes(q);
        if (!hit) return false;
      }
      if (filter === 'changed' && d.changes.length === 0) return false;
      if (filter === 'unchanged' && d.changes.length > 0) return false;
      if (filter === 'with_flag' && !d.has_flags) return false;
      if (flagFilter && !d.changes.some((c) => c.flags.includes(flagFilter))) return false;
      if (fieldFilter && !d.changes.some((c) => c.field === fieldFilter)) return false;
      return true;
    });
  }, [diffs, search, filter, flagFilter, fieldFilter]);

  const attentionRows = useMemo(
    () => diffs.filter((d) => d.has_flags),
    [diffs]
  );

  const rowsToShow = tab === 'attention' ? attentionRows : filtered;
  const totalPages = Math.max(1, Math.ceil(rowsToShow.length / PAGE_SIZE));
  const pageRows = rowsToShow.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  const resetFilters = () => {
    setFilter('all');
    setFlagFilter(null);
    setFieldFilter(null);
    setSearch('');
    setPage(0);
  };

  return (
    <div className="flex flex-col gap-4">
      {truncated && (
        <div className="bg-amber-50 border border-amber-200 text-amber-900 rounded-md px-3 py-2 text-[12px]">
          {t2('preview.truncated_warn', '⚠ Scope contains {total} products — analyzed first {n} for preview. Apply will process all of them.', { total: total_scope.toLocaleString(), n: analyzed.toLocaleString() })}
        </div>
      )}

      <SummaryCards
        summary={summary}
        onPickFlag={(f) => { setTab('all'); setFlagFilter(f); setFilter('all'); setPage(0); }}
        onPickField={(fid) => { setTab('all'); setFieldFilter(fid); setFilter('changed'); setPage(0); }}
        activeFlag={flagFilter}
        activeField={fieldFilter}
      />

      <div className="flex flex-wrap items-center gap-2 border-b border-border">
        <TabButton
          active={tab === 'attention'}
          onClick={() => { setTab('attention'); setPage(0); }}
          label={t('preview.tab_attention', 'Needs attention')}
          count={attentionRows.length}
          tone={attentionRows.length > 0 ? 'warn' : 'muted'}
        />
        <TabButton
          active={tab === 'all'}
          onClick={() => { setTab('all'); setPage(0); }}
          label={t('preview.tab_all', 'Browse all')}
          count={diffs.length}
          tone="muted"
        />
        <TabButton
          active={tab === 'summary'}
          onClick={() => { setTab('summary'); }}
          label={t('preview.tab_summary', 'Per-field summary')}
          count={summary.by_field.length}
          tone="muted"
        />
        <div className="flex-1" />
        <Button size="sm" variant="ghost" onClick={onDownloadCsv}>
          {t('preview.download_csv', '⬇ Download CSV')}
        </Button>
      </div>

      {tab === 'summary' ? (
        <PerFieldSummary summary={summary} />
      ) : (
        <>
          {tab === 'all' && (
            <div className="flex flex-wrap items-center gap-2 text-[12px]">
              <Input
                placeholder={t('preview.search_placeholder', 'Search by ID / name / REF…')}
                value={search}
                onChange={(e) => { setSearch(e.target.value); setPage(0); }}
                className="max-w-[260px]"
              />
              <select
                className="px-2 py-1.5 border border-border rounded-md bg-white text-[12px]"
                value={filter}
                onChange={(e) => { setFilter(e.target.value as RowFilter); setPage(0); }}
              >
                <option value="all">{t2('preview.row_all', 'All ({n})', { n: diffs.length })}</option>
                <option value="changed">{t2('preview.row_changed', 'Changed ({n})', { n: summary.will_change })}</option>
                <option value="unchanged">{t2('preview.row_unchanged', 'Unchanged ({n})', { n: summary.no_change })}</option>
                <option value="with_flag">{t2('preview.row_with_warnings', 'With warnings ({n})', { n: summary.with_flags })}</option>
              </select>
              {flagFilter && (
                <Badge variant="warning">
                  {t('preview.flag_label', 'Flag')}: {flagLabel(flagFilter)}
                  <button className="ml-1 text-slate-600 hover:text-slate-900" onClick={() => setFlagFilter(null)}>×</button>
                </Badge>
              )}
              {fieldFilter && (
                <Badge variant="primary">
                  {t('preview.field_label', 'Field')}: {fieldFilter}
                  <button className="ml-1 text-slate-600 hover:text-slate-900" onClick={() => setFieldFilter(null)}>×</button>
                </Badge>
              )}
              {(flagFilter || fieldFilter || filter !== 'all' || search) && (
                <button className="text-[11px] text-primary hover:underline" onClick={resetFilters}>{t('preview.reset_filters', 'Reset filters')}</button>
              )}
            </div>
          )}

          {tab === 'attention' && attentionRows.length === 0 && (
            <div className="text-center text-[13px] text-muted-foreground py-8 border border-dashed border-border rounded-md">
              {t2('preview.no_anomalies', '✓ No anomalies detected across {n} products.', { n: analyzed.toLocaleString() })}
            </div>
          )}

          <div className="flex flex-col gap-2">
            {pageRows.map((d) => (
              <DiffCard key={d.id_product} diff={d} />
            ))}
          </div>

          {rowsToShow.length > PAGE_SIZE && (
            <Pagination page={page} totalPages={totalPages} onChange={setPage} />
          )}
        </>
      )}
    </div>
  );
}

function TabButton({ active, onClick, label, count, tone }: {
  active: boolean; onClick: () => void; label: string; count: number; tone: 'warn' | 'muted';
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'px-3 py-2 text-[13px] font-medium border-b-2 -mb-px transition-colors',
        active ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-slate-900'
      )}
    >
      {label}
      <span className={cn(
        'ml-1.5 inline-flex items-center justify-center text-[10px] font-semibold rounded-full px-1.5 min-w-[18px] h-[18px]',
        active
          ? 'bg-primary/10 text-primary'
          : tone === 'warn' ? 'bg-amber-100 text-amber-800' : 'bg-muted text-muted-foreground'
      )}>
        {count.toLocaleString()}
      </span>
    </button>
  );
}

function SummaryCards({
  summary,
  onPickFlag,
  onPickField,
  activeFlag,
  activeField,
}: {
  summary: PreviewSummary;
  onPickFlag: (f: DiffFlag) => void;
  onPickField: (fid: string) => void;
  activeFlag: DiffFlag | null;
  activeField: string | null;
}) {
  const cards: Array<{ label: string; value: string; tone: 'base' | 'good' | 'warn' | 'error'; onClick?: () => void; active?: boolean }> = [
    { label: t('preview.card_in_scope',    'In scope'),    value: summary.total_scope.toLocaleString(), tone: 'base' },
    { label: t('preview.card_will_change', 'Will change'), value: summary.will_change.toLocaleString(), tone: 'good' },
    { label: t('preview.card_no_change',   'No change'),   value: summary.no_change.toLocaleString(),   tone: 'base' },
  ];
  if (summary.with_flags > 0) {
    cards.push({ label: t('preview.card_with_warnings', 'With warnings'), value: summary.with_flags.toLocaleString(), tone: 'warn' });
  }

  const flagCards: Array<{ flag: DiffFlag; label: string; count: number; tone: 'warn' | 'error' | 'info' }> = [];
  (Object.keys(summary.flag_counts) as DiffFlag[]).forEach((k) => {
    const count = summary.flag_counts[k];
    if (count > 0) {
      flagCards.push({ flag: k, label: flagLabel(k), count, tone: FLAG_META[k].tone });
    }
  });

  return (
    <div className="flex flex-col gap-3">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
        {cards.map((c) => (
          <div
            key={c.label}
            className={cn(
              'border border-border rounded-md px-3 py-2 bg-white',
              c.tone === 'good'  && 'border-green-300 bg-green-50',
              c.tone === 'warn'  && 'border-amber-300 bg-amber-50',
              c.tone === 'error' && 'border-red-300 bg-red-50'
            )}
          >
            <div className="text-[11px] uppercase tracking-wide text-muted-foreground">{c.label}</div>
            <div className={cn(
              'text-[20px] font-semibold leading-tight',
              c.tone === 'good'  && 'text-green-700',
              c.tone === 'warn'  && 'text-amber-700',
              c.tone === 'error' && 'text-red-700'
            )}>{c.value}</div>
          </div>
        ))}
      </div>

      {flagCards.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          <span className="text-[11px] text-muted-foreground self-center mr-1">{t('preview.filter_by_warning', 'Filter by warning:')}</span>
          {flagCards.map((f) => (
            <button
              key={f.flag}
              type="button"
              onClick={() => onPickFlag(f.flag)}
              className={cn(
                'px-2 py-1 text-[11px] rounded-full border transition-colors',
                activeFlag === f.flag
                  ? 'border-primary bg-primary/10 text-primary font-semibold'
                  : f.tone === 'error'
                    ? 'border-red-300 bg-red-50 text-red-800 hover:bg-red-100'
                    : f.tone === 'warn'
                      ? 'border-amber-300 bg-amber-50 text-amber-800 hover:bg-amber-100'
                      : 'border-blue-300 bg-blue-50 text-blue-800 hover:bg-blue-100'
              )}
            >
              {f.label} · {f.count}
            </button>
          ))}
        </div>
      )}

      {summary.by_field.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          <span className="text-[11px] text-muted-foreground self-center mr-1">{t('preview.filter_by_field', 'Filter by field:')}</span>
          {summary.by_field.map((f) => (
            <button
              key={f.field}
              type="button"
              onClick={() => onPickField(f.field)}
              className={cn(
                'px-2 py-1 text-[11px] rounded-full border transition-colors',
                activeField === f.field
                  ? 'border-primary bg-primary/10 text-primary font-semibold'
                  : 'border-border bg-muted/50 text-slate-700 hover:bg-muted'
              )}
            >
              {f.field_label} · {f.changes}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function PerFieldSummary({ summary }: { summary: PreviewSummary }) {
  if (summary.by_field.length === 0) {
    return <div className="text-[13px] text-muted-foreground">{t('preview.no_field_stats', 'No field stats — no fields changed.')}</div>;
  }
  return (
    <div className="overflow-x-auto border border-border rounded-md bg-white">
      <table className="w-full text-[13px]">
        <thead>
          <tr className="border-b border-border bg-muted/50 text-[11px] uppercase tracking-wide text-muted-foreground">
            <th className="text-left px-3 py-2">{t('preview.col_field', 'Field')}</th>
            <th className="text-right px-3 py-2">{t('preview.col_changes', 'Changes')}</th>
            <th className="text-right px-3 py-2">{t('preview.col_avg_len', 'Avg len (old → new)')}</th>
            <th className="text-right px-3 py-2">{t('preview.col_over_limit', 'Over limit')}</th>
            <th className="text-right px-3 py-2">{t('preview.col_clamped', 'Clamped')}</th>
            <th className="text-right px-3 py-2">{t('preview.col_invalid', 'Invalid format')}</th>
          </tr>
        </thead>
        <tbody>
          {summary.by_field.map((f) => (
            <tr key={f.field} className="border-b border-border last:border-0">
              <td className="px-3 py-2 font-medium">{f.field_label}</td>
              <td className="px-3 py-2 text-right">{f.changes.toLocaleString()}</td>
              <td className="px-3 py-2 text-right text-muted-foreground">
                {f.type === 'text' ? `${f.avg_old_len ?? '—'} → ${f.avg_new_len ?? '—'}${f.char_limit ? ` / ${f.char_limit}` : ''}` : '—'}
              </td>
              <td className={cn('px-3 py-2 text-right', f.over_limit > 0 && 'text-amber-700 font-semibold')}>
                {f.over_limit > 0 ? f.over_limit : '—'}
              </td>
              <td className={cn('px-3 py-2 text-right', f.clamped > 0 && 'text-amber-700 font-semibold')}>
                {f.clamped > 0 ? f.clamped : '—'}
              </td>
              <td className={cn('px-3 py-2 text-right', f.mismatches > 0 && 'text-red-700 font-semibold')}>
                {f.mismatches > 0 ? f.mismatches : '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {summary.collisions.length > 0 && (
        <div className="border-t border-border bg-red-50 px-3 py-2 text-[12px] text-red-800">
          <div className="font-semibold mb-1">{t2('preview.duplicate_values', 'Duplicate values across batch ({n} group{plural}):', { n: summary.collisions.length, plural: summary.collisions.length !== 1 ? 's' : '' })}</div>
          <ul className="list-disc pl-5 space-y-0.5">
            {summary.collisions.slice(0, 5).map((c, i) => (
              <li key={i}>
                <strong>{c.field_label}</strong> = <code className="bg-white px-1 rounded">{c.value || t('preview.empty', '(empty)')}</code> → {t2('preview.n_products', '{n} products', { n: c.product_count })}
              </li>
            ))}
            {summary.collisions.length > 5 && <li>{t2('preview.more_count', '+{n} more', { n: summary.collisions.length - 5 })}</li>}
          </ul>
        </div>
      )}
    </div>
  );
}

function DiffCard({ diff }: { diff: PreviewDiff }) {
  return (
    <div className={cn(
      'border rounded-md bg-white',
      diff.has_flags ? 'border-amber-300' : 'border-border'
    )}>
      <div className="flex items-center justify-between gap-2 px-3 py-2 bg-muted/50 border-b border-border">
        <div className="font-semibold text-[13px] min-w-0 truncate">
          #{diff.id_product} · {diff.name || t('preview.unnamed', '(unnamed)')}
        </div>
        <div className="text-[11px] text-muted-foreground flex-shrink-0">
          {diff.reference && `REF ${diff.reference} · `}{formatPrice(diff.price)}
          {diff.changes.length === 0 && <span className="ml-2 text-slate-500">{t('preview.no_change_inline', '· no change')}</span>}
        </div>
      </div>
      {diff.changes.length > 0 && (
        <div className="p-3 flex flex-col gap-2">
          {diff.changes.map((c, i) => (
            <div key={i} className="text-[12px]">
              <div className="flex items-center gap-2 mb-1">
                <span className="font-semibold text-slate-700">{c.field_label}</span>
                {c.flags.map((f) => (
                  <Badge key={f} variant={FLAG_META[f].tone === 'error' ? 'destructive' : FLAG_META[f].tone === 'warn' ? 'warning' : 'muted'}>
                    {flagLabel(f)}
                  </Badge>
                ))}
                {c.type === 'text' && c.old_len !== null && c.new_len !== null && (
                  <span className="text-[10px] text-muted-foreground">{t2('preview.chars_change', '{old} → {new} chars', { old: c.old_len, new: c.new_len })}</span>
                )}
              </div>
              <div className="grid grid-cols-1 gap-0.5">
                <div className="px-2 py-1 rounded bg-red-50 text-red-900 line-through text-[12px] break-words">{c.old || t('preview.empty', '(empty)')}</div>
                <div className="px-2 py-1 rounded bg-green-50 text-green-900 text-[12px] break-words">{c.new || t('preview.empty', '(empty)')}</div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function Pagination({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (p: number) => void }) {
  return (
    <div className="flex items-center justify-between pt-2 text-[12px]">
      <Button size="sm" variant="ghost" disabled={page === 0} onClick={() => onChange(page - 1)}>
        {t('preview.prev', '← Previous')}
      </Button>
      <span className="text-muted-foreground">{t2('preview.page_of', 'Page {p} of {t}', { p: page + 1, t: totalPages })}</span>
      <Button size="sm" variant="ghost" disabled={page >= totalPages - 1} onClick={() => onChange(page + 1)}>
        {t('preview.next', 'Next →')}
      </Button>
    </div>
  );
}
